### PR TITLE
Package Manager Refactor

### PR DESCRIPTION
**Pull request by pyr0ball**
In this refactor I changed the way CodeDog handles packagemanagers.

While there were some functions built for handling other package managers, all of the syntax, flags, arguments, and parsing were geared toward apt-get and dpkg.

The new workflow:

fetchPackages() gets passed packageData which matches the tags and if `sys` is specified as the fetchType, *only* the package name is passed into `checkAndUpgradeOSPackageVersions()`

Three bits of info are then defined, whether the package is installed, what version is currently installed, and the available package version from either online repos or extracted and parsed from the supplied package file (like a *deb or *rpm). This is handled via the `packageInstalled()` function.

packageInstalled() first determines which package manager would be best suited to the package passed to it. It sorts first based on if there is an extension supplied, and if that extension matches one of the package managers capable of handling it, that package manager is given priority over a repo-based manager (e.g. a package like vim.deb will get assigned `dpkg` in favor of `apt` as it includes an extension and is likely a file-based package). 

Another definition, `setPackageMgrFlags` uses the assigned package manager and defines the correct command strings via several variables that are concatenated within the `packageInstalled` function and used to query for packages using the correct manager and syntax for the package supplied.

I also added new functions that can be called directly for simplicity:

```python
packageInstall(packageName)
packageRemove(packageName)
packageUpdate(packageName)
```

### CODE REVIEW

**Comment by pyr0ball** [comment]
For clarity, as of the time of this writing, only apt/dpkg are functional. Other package manager definitions are actively being added

**Comment by pyr0ball** [comment]
Added fixes to address pip and pip package handling when the system is missing those

**Review by TiffanyLawrence — CHANGES_REQUESTED** [review]
Got the following error building minimalGame.dog: "/home/kt/devl/CodeDog/environmentMngr.py", line 26, in checkPackageStatus
    _packageToCheck = int(checkInstalled.stdout.read())
ValueError: invalid literal for int() with base 10: b''
 Traced it back to pmgrHandler.py lines 159-160.  If I comment these lines the libraries install and the program builds on my computer. Please correct.

Also, is environmentSetup.dog getting pushed?  It doesn't appear to do much beyond a basic 'hello world'.  Is there more to be added or was a test file that was pushed by mistake?

**Comment by pyr0ball** [comment]
Nice spotting on that!

I was attempting to add a failover for no matches, but it looks like it's just forcing a failure match instead.

Re: environmentSetup.dog, I added that initially to try building my own example (in order to get more familiar with the platform), but basically I just copied another example and renamed it. None of the tests I did produced the results I wanted so I just left it as is for now. It can be considered inert for the moment but I intend to use that for some more specific environment configurations once I learn the platform a bit better.

**Comment by pyr0ball** [comment]
@TiffanyLawrence would you be able to review one more time?

I just tested the new dependency resolution scheme successfully on Manjaro: 
image

**Comment by pyr0ball** [comment]
Figured out the problem with the `pacman` query. The way I'm having to string match for the installed vs available versions inverted the logical responses for the boolean 'is this package currently installed', so I had to make a little in-line `if` statement to correct it:

```bash
if [[ $(sudo pacman -Ss sdl2 | grep '/sdl2[^-,^_]' | grep -ic Installed) == 1 ]] ; then echo 0 ; else echo 1 ; fi
```

``` python
            elif commandType == "queryLocalInstall":
                pre = "if [[ $(sudo "
                post = " -Ss "+packageName+" | grep '/"+packageName+"[^-,^_]' | grep -ic 'installed') == 1 ]] ; then echo 0 ; else echo 1 ; fi"
```

**Review by TiffanyLawrence — APPROVED** [review]
Looks great!

**Pull request merged**
